### ISSUE TITLE
use also lsp tsserver for diagnostics

### ISSUE THREAD

**Issue by tkudlicka** [dmmulroy/tsc.nvim#41]
Hi, 

would be awesome if project diagnostic was done by tsserver lsp. I found that `tsserver` have `geterrForProject` or `geterr` which return diagnostics for file or project. I would also can make PR for.

**Comment by dmmulroy** [comment]
A couple things - 
1. `tsc.nvim` was actually originally created to _avoid_ `tsserver`. This is because
2. `tsserver`'s project-wide diagnostics are (were?) experimental, inconsistent, and slow.

If you can provide a PR that includes the ability + configuration to *opt-in* to using `tsserver`, along with benchmarks, I'd be happy to consider it.

**Comment by tkudlicka** [comment]
Ok, yeah its still experimental, i will try to provide it at weekend

**Comment by tkudlicka** [comment]
I found another solution. I used https://github.com/yioneko/vtsls lsp and in config of lsp enabled `tsserver.experimental.enableProjectDiagnostics` and now can found all typescript problems in diagnostics across workspace
